// Code generated by genfig (config built by merging 'default.yml' and 'development.local.toml') on 2019-07-01T23:51:00+02:00; DO NOT EDIT.

package config

var DevelopmentLocal = Config{
  Secrets: []string{""},
  Randomizer: ConfigRandomizer{
    Threshold: 0.75,
  },
  Apis: ConfigApis{
    Google: ConfigApisGoogle{
      Uri: "google.com",
    },
  },
  Version: "0.1.0",
  Project: "genfig",
  Server: ConfigServer{
    Port: 8080,
    Host: "localhost",
  },
  Db: ConfigDb{
    User: "",
    Pass: "",
    Uri: "mongdb://localhost:27017/${project}",
  },
}