// Code generated by genfig (config built from 'development.local.toml') on 2019-07-01T22:24:00+02:00; DO NOT EDIT.

package config

var DevelopmentLocal = Config{
	Server: ConfigServer{
		Port: 8080,
		Host: "localhost",
	},
	Db: ConfigDb{
		Uri: "mongdb://localhost:27017/${project}",
	},
}
