// Code generated by genfig (config built from 'development.yaml') on 2019-07-01T22:24:00+02:00; DO NOT EDIT.

package config

var Development = Config{
	Db: ConfigDb{
		Uri: "mongdb://${db.user}:${db.pass}@remotedb:27018/dev-db",
	},
	Version: "1",
	Server: ConfigServer{
		Host: "dev.mydomain.com",
		Port: 1234,
	},
}
