// Code generated by genfig (config built by merging 'default.yml' and 'development.yaml') on 2019-07-01T23:51:00+02:00; DO NOT EDIT.

package config

var Development = Config{
  Version: "1",
  Project: "genfig",
  Server: ConfigServer{
    Port: 1234,
    Host: "dev.mydomain.com",
  },
  Db: ConfigDb{
    User: "",
    Pass: "",
    Uri: "mongdb://${db.user}:${db.pass}@remotedb:27018/dev-db",
  },
  Secrets: []string{""},
  Randomizer: ConfigRandomizer{
    Threshold: 0.75,
  },
  Apis: ConfigApis{
    Google: ConfigApisGoogle{
      Uri: "google.com",
    },
  },
}