// Code generated by genfig (config built by merging 'default.yml' and '.env.local') on 2019-07-07T17:25:20+02:00; DO NOT EDIT.

package config

func init() {
	Envs.Local = Config{
		Version: "0.1.0",
		Server: ConfigServer{
			Port: 1212,
			Host: "localhost",
		},
		Randomizer: ConfigRandomizer{
			Threshold: 0.12345,
		},
		Wip: true,
		Project: "genfig",
		Db: ConfigDb{
			User: "chuck",
			Pass: "norris",
			Uri: "mongdb://localhos:27017/db",
		},
		Secrets: []string{"ChuckNorriscanwinagameofConnectFourinonlythreemoves"},
		Apis: ConfigApis{
			Google: ConfigApisGoogle{
				Uri: "google.com",
			},
		},
		LongDesc: ConfigLongDesc{
			En: "Long description",
			De: "Lange Beschreibung",
		},
	}
}
