// Code generated by genfig (config built by merging 'default.yml' and 'test.json') on 2019-11-19T10:45:54+01:00; DO NOT EDIT.

package config

func init() {
	Envs.Test = Config{
		Project: "genfig",
		Db: ConfigDb{
			Uri:  "mongdb://${db.user}:${db.pass}@remotedb:27018/proddb",
			User: "",
			Pass: "",
		},
		Randomizer: ConfigRandomizer{
			Threshold: 0.75,
		},
		Wip:     true,
		Version: "1-test",
		Server: ConfigServer{
			Host: "localhost",
			Port: 1234,
		},
		Secrets: []string{""},
		Apis: ConfigApis{
			Google: ConfigApisGoogle{
				Uri: "google.com",
			},
		},
		LongDesc: ConfigLongDesc{
			De: "Lange Beschreibung",
			En: "Long description",
		},
	}
	Envs.Test._map = map[string]interface{}{"apis": map[interface{}]interface{}{"google": map[interface{}]interface{}{"uri": "google.com"}}, "db": map[interface{}]interface{}{"pass": "", "uri": "mongdb://${db.user}:${db.pass}@remotedb:27018/proddb", "user": ""}, "longDesc": map[interface{}]interface{}{"de": "Lange Beschreibung", "en": "Long description"}, "project": "genfig", "randomizer": map[interface{}]interface{}{"threshold": 0.75}, "secrets": []interface{}{""}, "server": map[interface{}]interface{}{"host": "localhost", "port": 1234}, "version": "1-test", "wip": true}
}
