// Code generated by genfig (config built by merging 'default.yml' and 'production.json') on 2019-07-24T22:16:50+02:00; DO NOT EDIT.

package config

func init() {
	Envs.Production = Config{
		LongDesc: ConfigLongDesc{
			En: "Long description",
			De: "Lange Beschreibung",
		},
		Wip: true,
		Server: ConfigServer{
			Port: 1234,
			Host: "mydomain.com",
		},
		Secrets: []string{"ChuckNorriscanwinagameofConnectFourinonlythreemoves"},
		Apis: ConfigApis{
			Google: ConfigApisGoogle{
				Uri: "google.com",
			},
		},
		Randomizer: ConfigRandomizer{
			Threshold: 0.12345,
		},
		Version: "1",
		Project: "genfig",
		Db: ConfigDb{
			Uri:  "mongdb://${db.user}:${db.pass}@remotedb:27018/proddb",
			User: "chuck",
			Pass: "norris",
		},
	}
	Envs.Production._map = map[string]interface{}{"apis": map[interface{}]interface{}{"google": map[interface{}]interface{}{"uri": "google.com"}}, "db": map[interface{}]interface{}{"pass": "norris", "uri": "mongdb://${db.user}:${db.pass}@remotedb:27018/proddb", "user": "chuck"}, "longDesc": map[interface{}]interface{}{"de": "Lange Beschreibung", "en": "Long description"}, "project": "genfig", "randomizer": map[interface{}]interface{}{"threshold": 0.12345}, "secrets": []interface{}{"ChuckNorriscanwinagameofConnectFourinonlythreemoves"}, "server": map[interface{}]interface{}{"host": "mydomain.com", "port": 1234}, "version": "1", "wip": true}
}
