// Code generated by genfig (config built by merging 'default.yml' and 'development.yaml') on 2019-07-06T00:04:54+02:00; DO NOT EDIT.

package config

func init() {
  Envs.Development = Config{
    Project: "genfig",
    Server: ConfigServer{
      Port: 1234,
      Host: "dev.mydomain.com",
    },
    Db: ConfigDb{
      User: "",
      Pass: "",
      Uri: "mongdb://${db.user}:${db.pass}@remotedb:27018/dev-db",
    },
    Secrets: []string{""},
    Randomizer: ConfigRandomizer{
      Threshold: 0.75,
    },
    Version: "1",
    Apis: ConfigApis{
      Google: ConfigApisGoogle{
        Uri: "google.com",
      },
    },
    LongDesc: ConfigLongDesc{
      En: "Long description",
      De: "Lange Beschreibung",
    },
    Wip: true,
  }
}
