// Code generated by genfig (config built by merging 'default.yml' and 'default.yml'); DO NOT EDIT.

package config

func init() {
	Envs.Default = Config{
		Apis: ConfigApis{
			Google: ConfigApisGoogle{
				Uri: "google.com",
			},
		},
		Db: ConfigDb{
			Pass: "",
			Uri:  "mongdb://localhos:27017/db",
			User: "",
		},
		EmptyArray: []interface{}{},
		List:       []map[string]interface{}{map[string]interface{}{"a": 1, "b": 2}, map[string]interface{}{"a": 3, "b": 4}},
		LongDesc: ConfigLongDesc{
			De: "Lange Beschreibung",
			En: "Long description",
		},
		Project: "genfig",
		Randomizer: ConfigRandomizer{
			Threshold: 0.75,
		},
		Secrets: []string{""},
		Server: ConfigServer{
			Host: "localhost",
			Port: 1234,
		},
		Version: "0.1.0",
		Wip:     true,
	}
}
