// Code generated by genfig (config built by merging 'default.yml' and 'default.yml') on 2019-11-19T13:33:01+01:00; DO NOT EDIT.

package config

func init() {
	Envs.Default = Config{
		Project: "genfig",
		Secrets: []string{""},
		Wip:     true,
		List:    []map[interface{}]interface{}{map[interface{}]interface{}{"a": 1, "b": 2}, map[interface{}]interface{}{"a": 3, "b": 4}},
		Version: "0.1.0",
		Server: ConfigServer{
			Port: 1234,
			Host: "localhost",
		},
		Db: ConfigDb{
			Uri:  "mongdb://localhos:27017/db",
			User: "",
			Pass: "",
		},
		Randomizer: ConfigRandomizer{
			Threshold: 0.75,
		},
		Apis: ConfigApis{
			Google: ConfigApisGoogle{
				Uri: "google.com",
			},
		},
		LongDesc: ConfigLongDesc{
			En: "Long description",
			De: "Lange Beschreibung",
		},
		EmptyArray: []interface{}{},
	}
	Envs.Default._map = map[string]interface{}{"apis": map[interface{}]interface{}{"google": map[interface{}]interface{}{"uri": "google.com"}}, "db": map[interface{}]interface{}{"pass": "", "uri": "mongdb://localhos:27017/db", "user": ""}, "emptyArray": []interface{}{}, "list": []interface{}{map[interface{}]interface{}{"a": 1, "b": 2}, map[interface{}]interface{}{"a": 3, "b": 4}}, "longDesc": map[interface{}]interface{}{"de": "Lange Beschreibung", "en": "Long description"}, "project": "genfig", "randomizer": map[interface{}]interface{}{"threshold": 0.75}, "secrets": []interface{}{""}, "server": map[interface{}]interface{}{"host": "localhost", "port": 1234}, "version": "0.1.0", "wip": true}
}
