// Code generated by genfig (config built by merging 'default.yml' and 'default.yml') on 2019-07-23T22:25:20+02:00; DO NOT EDIT.

package config

func init() {
	Envs.Default = Config{
		Version: "0.1.0",
		Project: "genfig",
		Secrets: []string{""},
		Randomizer: ConfigRandomizer{
			Threshold: 0.75,
		},
		LongDesc: ConfigLongDesc{
			En: "Long description",
			De: "Lange Beschreibung",
		},
		Wip: true,
		Server: ConfigServer{
			Port: 1234,
			Host: "localhost",
		},
		Db: ConfigDb{
			User: "",
			Pass: "",
			Uri:  "mongdb://localhos:27017/db",
		},
		Apis: ConfigApis{
			Google: ConfigApisGoogle{
				Uri: "google.com",
			},
		},
	}
}
