// Code generated by genfig (config built by merging 'default.yml' and 'development.local.toml') on 2019-07-09T23:31:30+02:00; DO NOT EDIT.

package config

func init() {
	Envs.DevelopmentLocal = Config{
		Project: "genfig",
		Server: ConfigServer{
			Port: 8080,
			Host: "localhost",
		},
		Apis: ConfigApis{
			Google: ConfigApisGoogle{
				Uri: "google.com",
			},
		},
		Randomizer: ConfigRandomizer{
			Threshold: 0.75,
		},
		LongDesc: ConfigLongDesc{
			En: "Long description",
			De: "Lange Beschreibung",
		},
		Wip: true,
		Version: "0.1.0",
		Db: ConfigDb{
			User: "",
			Pass: "",
			Uri: "mongdb://localhost:27017/${project}",
		},
		Secrets: []string{""},
	}
}
