// Code generated by genfig (config built by merging 'default.yml' and 'development.yaml') on 2019-07-17T21:38:33+02:00; DO NOT EDIT.

package config

func init() {
	Envs.Development = Config{
		Wip:     true,
		Project: "genfig",
		Db: ConfigDb{
			User: "",
			Pass: "",
			Uri:  "mongdb://${db.user}:${db.pass}@remotedb:27018/dev-db",
		},
		Randomizer: ConfigRandomizer{
			Threshold: 0.75,
		},
		Apis: ConfigApis{
			Google: ConfigApisGoogle{
				Uri: "google.com",
			},
		},
		LongDesc: ConfigLongDesc{
			En: "Long description",
			De: "Lange Beschreibung",
		},
		Version: "1",
		Server: ConfigServer{
			Host: "dev.mydomain.com",
			Port: 1234,
		},
		Secrets: []string{""},
	}
}
