// Code generated by genfig (config built by merging 'default.yml' and 'production.json') on 2019-07-17T21:56:11+02:00; DO NOT EDIT.

package config

func init() {
	Envs.Production = Config{
		Version: "1",
		Project: "genfig",
		Server: ConfigServer{
			Port: 1234,
			Host: "mydomain.com",
		},
		Secrets: []string{""},
		Apis: ConfigApis{
			Google: ConfigApisGoogle{
				Uri: "google.com",
			},
		},
		Wip: true,
		Db: ConfigDb{
			User: "",
			Pass: "",
			Uri:  "mongdb://${db.user}:${db.pass}@remotedb:27018/proddb",
		},
		Randomizer: ConfigRandomizer{
			Threshold: 0.75,
		},
		LongDesc: ConfigLongDesc{
			En: "Long description",
			De: "Lange Beschreibung",
		},
	}
}
