// Code generated by genfig (config built by merging 'default.yml' and 'production.json') on 2019-11-19T10:45:54+01:00; DO NOT EDIT.

package config

func init() {
	Envs.Production = Config{
		Version: "1",
		Server: ConfigServer{
			Port: 1234,
			Host: "mydomain.com",
		},
		Secrets: []string{""},
		Apis: ConfigApis{
			Google: ConfigApisGoogle{
				Uri: "google.com",
			},
		},
		LongDesc: ConfigLongDesc{
			En: "Long description",
			De: "Lange Beschreibung",
		},
		Project: "genfig",
		Db: ConfigDb{
			User: "",
			Pass: "",
			Uri:  "mongdb://${db.user}:${db.pass}@remotedb:27018/proddb",
		},
		Randomizer: ConfigRandomizer{
			Threshold: 0.75,
		},
		Wip: true,
	}
	Envs.Production._map = map[string]interface{}{"apis": map[interface{}]interface{}{"google": map[interface{}]interface{}{"uri": "google.com"}}, "db": map[interface{}]interface{}{"pass": "", "uri": "mongdb://${db.user}:${db.pass}@remotedb:27018/proddb", "user": ""}, "longDesc": map[interface{}]interface{}{"de": "Lange Beschreibung", "en": "Long description"}, "project": "genfig", "randomizer": map[interface{}]interface{}{"threshold": 0.75}, "secrets": []interface{}{""}, "server": map[interface{}]interface{}{"host": "mydomain.com", "port": 1234}, "version": "1", "wip": true}
}
