// Code generated by genfig (config built by merging 'default.yml' and '.env.local') on 2019-07-23T23:30:42+02:00; DO NOT EDIT.

package config

func init() {
	Envs.Local = Config{
		Project: "genfig",
		Server: ConfigServer{
			Port: 1212,
			Host: "localhost",
		},
		Db: ConfigDb{
			Uri:  "mongdb://localhos:27017/db",
			User: "chuck",
			Pass: "norris",
		},
		Randomizer: ConfigRandomizer{
			Threshold: 0.12345,
		},
		LongDesc: ConfigLongDesc{
			En: "Long description",
			De: "Lange Beschreibung",
		},
		Version: "0.1.0",
		Secrets: []string{"ChuckNorriscanwinagameofConnectFourinonlythreemoves"},
		Apis: ConfigApis{
			Google: ConfigApisGoogle{
				Uri: "google.com",
			},
		},
		Wip: true,
	}
	Envs.Local._map = map[string]interface{}{"apis": map[interface{}]interface{}{"google": map[interface{}]interface{}{"uri": "google.com"}}, "db": map[interface{}]interface{}{"pass": "norris", "uri": "mongdb://localhos:27017/db", "user": "chuck"}, "longDesc": map[interface{}]interface{}{"de": "Lange Beschreibung", "en": "Long description"}, "project": "genfig", "randomizer": map[interface{}]interface{}{"threshold": 0.12345}, "secrets": []interface{}{"ChuckNorriscanwinagameofConnectFourinonlythreemoves"}, "server": map[interface{}]interface{}{"host": "localhost", "port": 1212}, "version": "0.1.0", "wip": true}
}
