// Code generated by genfig (config built by merging 'default.yml' and 'test.json') on 2019-07-23T22:25:20+02:00; DO NOT EDIT.

package config

func init() {
	Envs.Test = Config{
		Project: "genfig",
		Secrets: []string{""},
		Randomizer: ConfigRandomizer{
			Threshold: 0.75,
		},
		LongDesc: ConfigLongDesc{
			En: "Long description",
			De: "Lange Beschreibung",
		},
		Wip:     true,
		Version: "1-test",
		Db: ConfigDb{
			Uri:  "mongdb://localhos:27017/db",
			User: "",
			Pass: "",
		},
		Apis: ConfigApis{
			Google: ConfigApisGoogle{
				Uri: "google.com",
			},
		},
		Server: ConfigServer{
			Host: "localhost",
			Port: 1234,
		},
	}
}
