// Code generated by genfig on 2019-07-07T17:25:20+02:00; DO NOT EDIT.

package config

// Envs holds the envirnoment-specific configurations so that
// they can easily be accessed by e.g. Envs.Default
var Envs = struct{ 
	Default Config
	Development Config
	DevelopmentLocal Config
	Local Config
}{}

var envMap = map[string]*Config{
	"default": &Envs.Default,
	"development": &Envs.Development,
	"development.local": &Envs.DevelopmentLocal,
	"local": &Envs.Local,
}

// Get returns the config matching 'env' if found, otherwie the default config.
// The bool return value indicates, if a match was found (true) or the default config
// is returned
func Get(env string) (*Config, bool) {
	if c, ok := envMap[env]; ok {
		return c, true
	}
	return &Envs.Default, false
}
