// Code generated by genfig (schema built from 'default.yml') on 2019-07-01T23:51:00+02:00; DO NOT EDIT.

package config

type Config struct {
  Version string
  Project string
  Server ConfigServer
  Db ConfigDb
  Secrets []string
  Randomizer ConfigRandomizer
  Apis ConfigApis
}
type ConfigApisGoogle struct {
  Uri string
}
type ConfigServer struct {
  Port int64
  Host string
}
type ConfigRandomizer struct {
  Threshold float64
}
type ConfigDb struct {
  User string
  Pass string
  Uri string
}
type ConfigApis struct {
  Google ConfigApisGoogle
}
