// Code generated by genfig (schema built from 'default.yml') on 2019-07-01T22:24:00+02:00; DO NOT EDIT.

package config

type Config struct {
	Project    string
	Server     ConfigServer
	Db         ConfigDb
	Secrets    []string
	Randomizer ConfigRandomizer
	Apis       ConfigApis
	Version    string
}
type ConfigServer struct {
	Host string
	Port int64
}
type ConfigRandomizer struct {
	Threshold float64
}
type ConfigApisGoogle struct {
	Uri string
}
type ConfigApis struct {
	Google ConfigApisGoogle
}
type ConfigDb struct {
	User string
	Pass string
	Uri  string
}
