// Code generated by genfig (schema built from 'default.yml') on 2019-07-01T12:51:25+02:00; DO NOT EDIT.

package config

type ConfigRandomizer struct {
  Threshold float64
}
type ConfigApis struct {
  Google ConfigApisGoogle
}
type ConfigApisGoogle struct {
  Uri string
}
type ConfigServer struct {
  Port int64
  Host string
}
type ConfigDb struct {
  User string
  Pass string
  Uri string
}
