// Code generated by genfig on 2019-07-23T22:25:20+02:00; DO NOT EDIT.

package config

import (
	"os"
)

// Current is the current config, selected by the curren env and
// updated by the availalbe env vars
var Current *Config

// This init tries to retrieve the current environment via the
// common env var 'ENV' and applies activated plugins
func init() {
	Current, _ = Get(os.Getenv("ENV"))

	// calling plugin substitutor
	Current.Substitute()

	// calling plugin update_from_env
	Current.UpdateFromEnv()

}
