// Code generated by genfig (config built from '.env.local') on 2019-07-01T22:24:00+02:00; DO NOT EDIT.

package config

var Local = Config{
  Db: ConfigDb{
    Pass: "norris",
    User: "chuck",
  },
  Secrets: []string{"ChuckNorriscanwinagameofConnectFourinonlythreemoves"},
}