// Code generated by genfig (config built by merging 'default.yml' and '.env.local') on 2019-07-01T23:51:00+02:00; DO NOT EDIT.

package config

var Local = Config{
  Project: "genfig",
  Server: ConfigServer{
    Port: 1212,
    Host: "localhost",
  },
  Db: ConfigDb{
    User: "chuck",
    Pass: "norris",
    Uri: "mongdb://localhos:27017/db",
  },
  Secrets: []string{"ChuckNorriscanwinagameofConnectFourinonlythreemoves"},
  Randomizer: ConfigRandomizer{
    Threshold: 0.12345,
  },
  Apis: ConfigApis{
    Google: ConfigApisGoogle{
      Uri: "google.com",
    },
  },
  Version: "0.1.0",
}