// Code generated by genfig (config built from '.env.local') on 2019-07-01T12:51:25+02:00; DO NOT EDIT.

package config

var Local = Config{
  Secrets: []string{"ChuckNorriscanwinagameofConnectFourinonlythreemoves"},
  Db: ConfigDb{
    User: "chuck",
    Pass: "norris",
  },
}