// Code generated by genfig plugin 'map'; DO NOT EDIT.

package config

import "encoding/json"

func (c *Config) AsMap() map[string]interface{} {
	marshaled, err := json.Marshal(c)
	if err != nil {
		return nil
	}
	m := map[string]interface{}{}
	if err := json.Unmarshal(marshaled, &m); err != nil {
		return nil
	}
	return m
}
