// Code generated by genfig plugin 'config_test' on 2019-07-09T23:31:30+02:00; DO NOT EDIT.

package config

import "testing"

func Test_CurrentConfig(t *testing.T) {
	if Current == nil {
		t.Error("Current config is nil")
	}
}
