// Code generated by genfig plugin 'config_test' on 2019-11-19T13:33:01+01:00; DO NOT EDIT.

package config

import "testing"

func Test_CurrentConfig(t *testing.T) {
	if Current == nil {
		t.Error("Current config is nil")
	}
}
