// Code generated by genfig (schema built from 'default.yml') on 2019-11-19T10:45:54+01:00; DO NOT EDIT.

package config

type Config struct {
	Db         ConfigDb
	Randomizer ConfigRandomizer
	Wip        bool
	Project    string
	Server     ConfigServer
	Secrets    []string
	Apis       ConfigApis
	LongDesc   ConfigLongDesc
	Version    string
	_map       map[string]interface{}
}

type ConfigApis struct {
	Google ConfigApisGoogle
}

type ConfigApisGoogle struct {
	Uri string
}

type ConfigDb struct {
	Pass string
	Uri  string
	User string
}

type ConfigLongDesc struct {
	En string
	De string
}

type ConfigRandomizer struct {
	Threshold float64
}

type ConfigServer struct {
	Port int64
	Host string
}
