// Code generated by genfig (schema built from 'default.yml') on 2019-07-17T21:38:33+02:00; DO NOT EDIT.

package config

type Config struct {
	Apis       ConfigApis
	LongDesc   ConfigLongDesc
	Version    string
	Server     ConfigServer
	Secrets    []string
	Wip        bool
	Project    string
	Db         ConfigDb
	Randomizer ConfigRandomizer
}

type ConfigApis struct {
	Google ConfigApisGoogle
}

type ConfigApisGoogle struct {
	Uri string
}

type ConfigDb struct {
	User string
	Pass string
	Uri  string
}

type ConfigLongDesc struct {
	En string
	De string
}

type ConfigRandomizer struct {
	Threshold float64
}

type ConfigServer struct {
	Port int64
	Host string
}
