package genfig

import (
	"io"
	"text/template"
	"time"
)

var (
	headerTpl = template.Must(template.New("header").Parse(`// Code generated by {{.Cmd}} on {{.Created}}; DO NOT EDIT.

package {{.Pkg}}

`))
)

func writeHeader(w io.Writer, pkg string, cmd string) error {
	return headerTpl.Execute(w, struct {
		Pkg     string
		Cmd     string
		Created string
	}{Pkg: pkg, Cmd: cmd, Created: time.Now().Format(time.RFC3339)})
}
