version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: make test
      - run: make build

workflows:
  version: 2
  build-workflow:
    jobs:
      - build