// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/base.qtpl:1
package templates

//line templates/base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/base.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/base.qtpl:1
func StreamHeader(qw422016 *qt422016.Writer, pkg string, cmd string) {
//line templates/base.qtpl:2
	qw422016.N().S(`// Code generated by `)
//line templates/base.qtpl:2
	qw422016.N().S(cmd)
//line templates/base.qtpl:2
	qw422016.N().S(`; DO NOT EDIT.

package `)
//line templates/base.qtpl:4
	qw422016.N().S(pkg)
//line templates/base.qtpl:4
	qw422016.N().S(`
`)
//line templates/base.qtpl:5
}

//line templates/base.qtpl:5
func WriteHeader(qq422016 qtio422016.Writer, pkg string, cmd string) {
//line templates/base.qtpl:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base.qtpl:5
	StreamHeader(qw422016, pkg, cmd)
//line templates/base.qtpl:5
	qt422016.ReleaseWriter(qw422016)
//line templates/base.qtpl:5
}

//line templates/base.qtpl:5
func Header(pkg string, cmd string) string {
//line templates/base.qtpl:5
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base.qtpl:5
	WriteHeader(qb422016, pkg, cmd)
//line templates/base.qtpl:5
	qs422016 := string(qb422016.B)
//line templates/base.qtpl:5
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base.qtpl:5
	return qs422016
//line templates/base.qtpl:5
}
